# Generated by Django 6.0.3 on 2026-03-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/')),
                ('comment', models.TextField(blank=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('checked', 'Checked'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
            ],
        ),
    ]
